name: CI
  build:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      
      # Build
      
      - name: Percy Test
        run: cd example-percy-ember-master
        run: echo "hi"
        run: npm i
        run: npm run test
